INSERT INTO genres (id, name, slug, description) VALUES
('1','Action','action','\N'),
('2','Adventure','adventure','\N'),
('3','Comedy','comedy','\N'),
('5','Sci-Fi','sci-fi','\N'),
('6','Space','space','\N'),
('7','Mystery','mystery','\N'),
('8','Magic','magic','\N'),
('9','Supernatural','supernatural','\N'),
('10','Police','police','\N'),
('13','Sports','sports','\N'),
('14','Romance','romance','\N'),
('20','Psychological','psychological','\N'),
('21','Thriller','thriller','\N'),
('22','Martial Arts','martial-arts','\N'),
('23','Super Power','super-power','\N'),
('24','School','school','\N'),
('25','Ecchi','ecchi','\N'),
('26','Vampire','vampire','\N'),
('27','Historical','historical','\N'),
('28','Military','military','\N'),
('29','Dementia','dementia','\N'),
('30','Mecha','mecha','\N'),
('31','Demons','demons','\N'),
('32','Samurai','samurai','\N'),
('34','Harem','harem','\N'),
('35','Music','music','\N'),
('36','Parody','parody','\N'),
('38','Game','game','\N'),
('39','Shounen','Ai','shounen-ai','\N'),
('40','Kids','kids','\N'),
('41','Hentai','hentai','\N'),
('42','Yuri','yuri','\N'),
('43','Yaoi','yaoi','\N'),
('44','Anime Influenced','anime-influenced','\N'),
('45','Gender Bender','gender-bender','\N'),
('46','Doujinshi','doujinshi','\N'),
('47','Mahou Shoujo','mahou-shoujo','Magical Girls','\N'),
('17','Racing','racing','\N'),
('48','Mahou Shounen','mahou-shounen','Magical Boys','\N'),
('49','Gore','gore','\N'),
('11','Fantasy','fantasy','\N'),
('19','Horror','horror','\N'),
('37','Shoujo','Ai','shoujo-ai','\N'),
('16','Slice of Life','slice-of-life','\N'),
('4','Drama','drama','\N');